/* Get Public Gists */
export const GET_PUBLIC_GISTS_REQUEST = "GET_PUBLIC_GISTS_REQUEST";
export const GET_PUBLIC_GISTS_SUCCESS = "GET_PUBLIC_GISTS_SUCCESS";
export const GET_PUBLIC_GISTS_FAILED = "GET_PUBLIC_GISTS_FAILED";

/* Get Public Gists By Name */
export const GET_PUBLIC_GISTS_BY_NAME_REQUEST =
  "GET_PUBLIC_GISTS_BY_NAME_REQUEST";
export const GET_PUBLIC_GISTS_BY_NAME_SUCCESS =
  "GET_PUBLIC_GISTS_BY_NAME_SUCCESS";
export const GET_PUBLIC_GISTS_BY_NAME_FAILED =
  "GET_PUBLIC_GISTS_BY_NAME_FAILED";
